function handleClick() {
  //this functions runs when the button is clicked
  axios.get(apiURL).then(showAnswer);
  function showAnswer(response) {
    //when the button is clicked, the joke is being generated by this function
    let helloWorld = document.querySelector("#helloWorld");
    if (response) {
      //if the joke is already generated it will be typewritted
      //helloWorld.innerHTML = `${response.data.answer}`;
      new Typewriter(helloWorld, {
        strings: `${response.data.answer}`,
        autoStart: true,
        delay: 40,
      });
    } else {
      // else, the sentence bellow will be written in meantime
      helloWorld.innerHTML = "Your joke is being generated, please wait.";
    }
  }
}

let butttonElement = document.querySelector("#my-button"); //select button
butttonElement.addEventListener("click", handleClick); //when the button is clicked, the handleClick function is called

let apiKey = "6ddtf02cf3a61b83b8oaf010eba5f493";
let context = "provide just the joke, nothing else";
let prompt = "tell me a joke about animals, please";
let apiURL = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;
